# Generated by Django 4.2.13 on 2024-05-28 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogue", "0027_attributeoption_code_attributeoptiongroup_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductElasticsearchSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductFacet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field", models.CharField(choices=[("", "")], max_length=255)),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="The label is typically shown above all available choices for this facet. By default is uses the field name.",
                        max_length=255,
                    ),
                ),
                (
                    "facet_type",
                    models.CharField(
                        choices=[("term", "Term"), ("range", "Range")],
                        default="term",
                        max_length=20,
                    ),
                ),
                (
                    "formatter",
                    models.CharField(
                        blank=True,
                        choices=[("", "")],
                        help_text="If you select a formatter, the values returned from Elasticsearch will be formatted using this function.",
                        max_length=255,
                    ),
                ),
                (
                    "disabled_categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="If this facet should be hidden for a specific set of categories, you can choose them here. If you leave this (and enabled categories) empty, the facet will be enabled for all categories.",
                        related_name="disabled_facets",
                        to="catalogue.category",
                    ),
                ),
                (
                    "enabled_categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="If this facet is for a specific set of categories, you can choose them here. If you leave this (and disabled categories) empty, the facet will be enabled for all categories.",
                        related_name="enabled_facets",
                        to="catalogue.category",
                    ),
                ),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facets",
                        to="django_oscar_es.productelasticsearchsettings",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductSearchField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field", models.CharField(choices=[("", "")], max_length=255)),
                (
                    "boost",
                    models.FloatField(
                        default=1.0, help_text="The boost factor for this field."
                    ),
                ),
                (
                    "disabled",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, this field will not be used for searching.",
                    ),
                ),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_fields",
                        to="django_oscar_es.productelasticsearchsettings",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductFacetRangeOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="The label for this range option. Eg; '10 to 50'",
                        max_length=255,
                    ),
                ),
                (
                    "range_type",
                    models.CharField(
                        choices=[
                            ("integer", "Integer"),
                            ("float", "Float"),
                            ("double", "Double"),
                            ("decimal", "Decimal"),
                            ("date", "Date"),
                            ("datetime", "Datetime"),
                        ],
                        default="integer",
                        help_text="The type of range this option represents.",
                        max_length=20,
                    ),
                ),
                (
                    "from_value",
                    models.CharField(
                        blank=True,
                        help_text="The 'from' value for this range option.",
                        max_length=255,
                    ),
                ),
                (
                    "to_value",
                    models.CharField(
                        blank=True,
                        help_text="The 'to' value for this range option.",
                        max_length=255,
                    ),
                ),
                (
                    "facet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="range_options",
                        to="django_oscar_es.productfacet",
                    ),
                ),
            ],
        ),
    ]
