# Generated by Django 4.2.13 on 2024-05-21 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogue", "0027_attributeoption_code_attributeoptiongroup_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductElasicSearchConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "search_fields",
                    models.TextField(
                        default="title,description,upc",
                        help_text="Enter the fields which should be used for search. You can enter multiple fields separated by comma.",
                    ),
                ),
                (
                    "auto_complete_fields",
                    models.TextField(
                        default="title,upc",
                        help_text="Enter the fields which should be used for auto-complete. You can enter multiple fields separated by comma.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product ElasticSearch Configuration",
                "verbose_name_plural": "Product ElasticSearch Configuration",
            },
        ),
        migrations.CreateModel(
            name="AttributeFacet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attribute_code",
                    models.CharField(choices=[("", "")], max_length=255, unique=True),
                ),
                (
                    "facet_type",
                    models.CharField(
                        choices=[("term", "Term"), ("range", "Range")],
                        default="term",
                        max_length=20,
                    ),
                ),
                (
                    "ranges",
                    models.TextField(
                        blank=True,
                        help_text="Enter the ranges for this facet. You can enter multiple ranges separated by comma. Each range should be in the format 'from|to'.",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Enter the label for this facet.", max_length=255
                    ),
                ),
                (
                    "searchable",
                    models.BooleanField(
                        default=False,
                        help_text="If you enable this, a search bar will be shown under this facet so you can filter the facet values. This is useful for large facets with a lot of values.",
                    ),
                ),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_facets",
                        to="django_oscar_es.productelasicsearchconfiguration",
                    ),
                ),
                (
                    "disabled_categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="If this facet should be hidden for a specific set of categories, you can choose them here. If you leave this (and disabled categories) empty, the facet will be enabled for all categories.",
                        related_name="disabled_facets",
                        to="catalogue.category",
                    ),
                ),
                (
                    "enabled_categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="If this facet is for a specific set of categories, you can choose them here. If you leave this (and disabled categories) empty, the facet will be enabled for all categories.",
                        related_name="enabled_facets",
                        to="catalogue.category",
                    ),
                ),
            ],
        ),
    ]
