# Generated by Django 4.2.13 on 2024-06-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_oscar_es", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productfacet",
            name="size",
            field=models.IntegerField(
                default=10, help_text="The number of facet values to return."
            ),
        ),
        migrations.AlterField(
            model_name="productfacetrangeoption",
            name="range_type",
            field=models.CharField(
                choices=[
                    ("integer", "Integer"),
                    ("float", "Float"),
                    ("double", "Double"),
                    ("decimal", "Decimal"),
                    ("date", "Date"),
                ],
                default="integer",
                help_text="The type of range this option represents.",
                max_length=20,
            ),
        ),
    ]
